/*
 * MorphSnap -- tests/Integration/TestDatasetIntegration.cpp
 * Integration tests for dataset generation pipeline.
 */

#define _USE_MATH_DEFINES
#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_approx.hpp>

#include <cmath>

#include "AI/Dataset/DatasetGeneratorV2.h"
#include "AI/Dataset/DatasetGeneratorV3.h"

#include <juce_core/juce_core.h>
#include <juce_audio_basics/juce_audio_basics.h>

using Catch::Approx;
using namespace morphsnap;

// =============================================================================
//  V2 Pipeline Integration Tests
// =============================================================================

TEST_CASE("DatasetGeneratorV2: initialization succeeds", "[dataset][integration][v2]")
{
    DatasetGeneratorV2 generator;

    DatasetGeneratorConfig config;
    config.outputDirectory = juce::File::getSpecialLocation(juce::File::tempDirectory)
                                .getChildFile("morphsnap_test_dataset");
    config.totalSamples = 10;
    config.randomSeed = 42;
    config.sampleRate = 48000.0;
    config.blockSize = 512;
    config.dryRun = true;

    generator.setConfig(config);

    // Note: initialize() requires audio library and plugin chain to be set up
    // For basic config validation, just check that config was accepted
    REQUIRE(generator.getConfig().totalSamples == 10);
}

TEST_CASE("DatasetGeneratorV2: parameter sampling works", "[dataset][integration][v2]")
{
    DatasetGeneratorV2 generator;

    DatasetGeneratorConfig config;
    config.totalSamples = 100;
    config.randomSeed = 42;
    config.samplingConfig.sampleCount = 100;
    config.samplingConfig.seed = 42;

    generator.setConfig(config);

    // Generate LHS samples through the sampler
    auto& sampler = generator.getSampler();
    auto samples = sampler.generateLHS(config.samplingConfig, 10);

    REQUIRE(samples.size() == 100);
    for (const auto& sample : samples) {
        REQUIRE(sample.size() == 10);
        for (float val : sample) {
            REQUIRE(val >= 0.0f);
            REQUIRE(val <= 1.0f);
        }
    }
}

// =============================================================================
//  V3 Pipeline Integration Tests
// =============================================================================

TEST_CASE("DatasetGeneratorV3: configuration accepted", "[dataset][integration][v3]")
{
    DatasetGeneratorV3 generator;

    V3GenerationConfig config;
    config.baseConfig.totalSamples = 10;
    config.baseConfig.randomSeed = 42;
    config.workerThreads = 2;
    config.batchSize = 5;

    REQUIRE_NOTHROW(generator.setConfig(config));
}

TEST_CASE("DatasetGeneratorV3: can use V2 parameter sets", "[dataset][integration][v3]")
{
    // This tests that V3 can accept parameter sets generated by V2's sampler

    DatasetGeneratorV2 v2;
    DatasetGeneratorConfig v2Config;
    v2Config.samplingConfig.sampleCount = 10;
    v2Config.samplingConfig.seed = 42;

    v2.setConfig(v2Config);

    // Generate parameters
    auto params = v2.getSampler().generateLHS(v2Config.samplingConfig, 5);
    REQUIRE(params.size() == 10);

    // Verify V3 config can be created with same dimensions
    V3GenerationConfig v3Config;
    v3Config.baseConfig = v2Config;
    v3Config.workerThreads = 1;
    v3Config.batchSize = 5;

    DatasetGeneratorV3 v3;
    REQUIRE_NOTHROW(v3.setConfig(v3Config));
}

// =============================================================================
//  Feature Extraction Integration Tests
// =============================================================================

TEST_CASE("FeatureExtractor: full extraction pipeline", "[dataset][integration][features]")
{
    FeatureExtractor extractor;
    ExtractionConfig config;
    config.sampleRate = 48000.0;
    config.frameSize = 2048;
    config.hopSize = 512;
    config.computeMFCC = true;
    config.computeChroma = true;
    config.computeFrameLevel = true;

    // Create a 2-second stereo test signal
    juce::AudioBuffer<float> buffer(2, 96000);

    // Left channel: 440 Hz sine
    for (int i = 0; i < 96000; ++i)
        buffer.setSample(0, i, std::sin(2.0 * M_PI * 440.0 * i / 48000.0) * 0.5f);

    // Right channel: 880 Hz sine
    for (int i = 0; i < 96000; ++i)
        buffer.setSample(1, i, std::sin(2.0 * M_PI * 880.0 * i / 48000.0) * 0.5f);

    auto features = extractor.extract(buffer, config);

    // Verify all feature categories populated
    REQUIRE(features.spectral.mfcc.size() == 13);
    REQUIRE(features.spectral.chroma.size() == 12);
    REQUIRE(features.temporal.rmsEnergy > -100.0f);  // dB value, non-silent audio
    REQUIRE(features.perceptual.lufs < 0.0f);

    // Verify frame-level features
    REQUIRE(features.frameCount > 0);
    REQUIRE(features.spectralFrames.size() > 0);
}
