/*
 * More-Phi — Core/HarmonicExciter.cpp
 */
#include "HarmonicExciter.h"
#include <algorithm>
#include <cmath>

namespace more_phi {

static constexpr float kPi = 3.14159265358979f;

HarmonicExciter::HarmonicExciter()
{
    hpState_.fill({0.f, 0.f});
}

void HarmonicExciter::setCutoff(float hz) noexcept
{
    cutoffHz_.store(hz, std::memory_order_relaxed);
    // Coefficients are recomputed in prepare(); if called at runtime,
    // they'll update on the next prepare() call. For live changes call
    // recomputeCoefficients() explicitly from the message thread.
    recomputeCoefficients();
}

void HarmonicExciter::prepare(double sampleRate, int maxBlockSize)
{
    sampleRate_ = sampleRate;

    // ENHANCERS-1: 4x-oversample the saturation stage so the harmonics generated
    // by fastTanh don't alias back into the audible band. The HP biquad runs at
    // the oversampled rate, so its coefficients are computed for processRate_.
    os_.setFactor(OversamplingFactor::x4);
    os_.prepare(maxBlockSize, kMaxChannels, sampleRate);
    processRate_ = sampleRate * static_cast<double>(os_.getActiveFactor());

    recomputeCoefficients();
    reset();
}

void HarmonicExciter::reset() noexcept
{
    hpState_.fill({0.f, 0.f});
    os_.reset();
}

void HarmonicExciter::recomputeCoefficients() noexcept
{
    // 2nd-order Butterworth HP using bilinear transform
    const float fc   = cutoffHz_.load(std::memory_order_relaxed);
    const float fs   = static_cast<float>(processRate_);  // ENHANCERS-1: biquad runs at os rate
    const float wc   = std::tan(kPi * fc / fs);
    const float wc2  = wc * wc;
    const float sq2  = 1.41421356f;                 // sqrt(2)
    const float norm = 1.f / (1.f + sq2 * wc + wc2);

    b0_ =  norm;
    b1_ = -2.f * norm;
    b2_ =  norm;
    a1_ =  2.f * (wc2 - 1.f) * norm;
    a2_ =  (1.f - sq2 * wc + wc2) * norm;
}

void HarmonicExciter::processBlock(juce::AudioBuffer<float>& buf) noexcept
{
    if (!enabled_.load(std::memory_order_relaxed)) return;

    const float drive  = driveLinear_.load(std::memory_order_relaxed);
    const float wet    = dryWet_.load(std::memory_order_relaxed);
    const float dry    = 1.0f - wet;
    const int   nch    = std::min(buf.getNumChannels(), kMaxChannels);

    // ENHANCERS-1 FIX: oversample the saturation stage 4x so the harmonics
    // generated by fastTanh don't alias back into the audible band. The whole
    // signal (HP + drive + tanh + dry/wet mix) is processed in the oversampled
    // domain and downsampled in one round-trip, so dry and wet share the same
    // path and there is no dry/wet latency misalignment. The HP biquad runs at
    // the 4x rate (coefficients computed for processRate_).
    juce::dsp::AudioBlock<float> inputBlock(buf);
    auto osBlock = os_.upsample(inputBlock);
    const int osNs = static_cast<int>(osBlock.getNumSamples());

    for (int ch = 0; ch < nch; ++ch)
    {
        float* d = osBlock.getChannelPointer(static_cast<size_t>(ch));
        BiquadState& st = hpState_[ch];

        for (int i = 0; i < osNs; ++i)
        {
            const float in = d[i];

            // Transposed direct-form II biquad (HP) at the oversampled rate
            const float hp  = b0_ * in + st.z1;
            st.z1 = b1_ * in - a1_ * hp + st.z2;
            st.z2 = b2_ * in - a2_ * hp;

            // Drive + soft saturation via Padé tanh (bounded; see fastTanh doc)
            const float driven  = hp * drive;
            const float excited = fastTanh(driven);

            d[i] = dry * in + wet * excited;
        }
    }

    juce::dsp::AudioBlock<float> outputBlock(buf);
    os_.downsample(outputBlock);
}

} // namespace more_phi
