/*
 * More-Phi — Core/TruePeakEstimator.h
 *
 * ITU-R BS.1770-4 True Peak (inter-sample peak, ISP) estimator.
 *
 * Uses a simple 4x polyphase FIR upsampler (64-tap per phase) to detect
 * inter-sample peaks that standard sample-domain peak meters miss.
 * This is an intentionally lightweight implementation that does not depend
 * on the full OversamplingWrapper — it is designed to be instantiated
 * independently by both TruePeakEstimator and BrickwallLimiter.
 *
 * Method (EBU R128 / ITU-R BS.1770-4 Annex 2):
 *   Upsample by 4 using an FIR interpolation filter (zero-phase, linear-phase).
 *   Find the absolute maximum over all upsampled samples per block.
 *
 * Accuracy (AUDIT Stage 3 / R3 / W10 fix, 2026-06-25, reconciled with
 * TruePeakEstimator.cpp + TestTruePeakEstimator.cpp):
 *   - Prototype: 256-tap linear-phase FIR low-pass at fc = fs_up/8 (0.125 of
 *     the upsampled Nyquist), Kaiser window β=8.6 (~80 dB stopband).
 *   - Polyphase-decomposed to 4 phases × 64 taps (kFIRTaps = 64).
 *   - Closes the ~25 dB near-Nyquist under-read the prior 48-tap β=5.0
 *     prototype (12 taps/phase) exhibited; the estimator now tracks the
 *     independent reference reconstruction to ~0.02–0.1 dBTP across DC, step,
 *     near-Nyquist, and two-tone signals.
 *   - This is a streaming-safe ISP estimator, NOT a certified BS.1770-4 meter
 *     (no fixed-point reference device trace). For certification, validate
 *     against a TC Electronic LM2n / Nugen trace.
 *
 * Thread safety:
 *   processBlock() — audio thread only, noexcept.
 *   getTruePeak_dBTP() — atomic read, safe from any thread.
 *   prepare() — message thread only.
 */
#pragma once

#include <atomic>
#include <array>
#include <cmath>
#include <juce_audio_basics/juce_audio_basics.h>

namespace more_phi {

class TruePeakEstimator
{
public:
    static constexpr int kMaxChannels  = 2;
    static constexpr int kUpsampleFactor = 4;
    // Taps per polyphase sub-filter. 64 taps/phase ⇒ a 256-tap linear-phase
    // prototype (4×64) — measurement-grade per ITU-R BS.1770-4 / EBU R128 App.2,
    // matching the reference reconstruction in TestTruePeakEstimator.cpp. Closes
    // the ~25 dB near-Nyquist under-read the prior 48-tap β=5.0 prototype had.
    // (Regenerate via scripts/generate_truepeak_coeffs.py.)
    static constexpr int kFIRTaps = 64;

    TruePeakEstimator();

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    /** Prepare filter state for the given sample rate and block size. */
    void prepare(double sampleRate, int maxBlockSize) noexcept;

    /** Reset filter delay lines. */
    void reset() noexcept;

    // ── Audio thread ──────────────────────────────────────────────────────────

    /**
     * Process a block. Updates the true peak atomics.
     * noexcept — no allocations; pure polyphase FIR arithmetic.
     */
    void processBlock(const juce::AudioBuffer<float>& buf) noexcept;

    // ── Results (any thread) ──────────────────────────────────────────────────

    /** True peak of channel 0 (L) in dBTP. */
    [[nodiscard]] float getTruePeak_L_dBTP() const noexcept { return peakL_.load(std::memory_order_relaxed); }

    /** True peak of channel 1 (R) in dBTP. */
    [[nodiscard]] float getTruePeak_R_dBTP() const noexcept { return peakR_.load(std::memory_order_relaxed); }

    /** Stereo-linked maximum true peak in dBTP. */
    [[nodiscard]] float getTruePeak_dBTP()   const noexcept { return peak_.load(std::memory_order_relaxed); }

    /** Linear maximum true peak (0.0–∞). */
    [[nodiscard]] float getTruePeakLinear()  const noexcept { return peakLin_.load(std::memory_order_relaxed); }

    /**
     * Compute the true-peak (maximum over all kUpsampleFactor polyphase phases)
     * of the sample at position @p pos in a delay line of length @p delayLen.
     * Reads the kFIRTaps most-recent samples ending at @p pos.
     *
     * Used by BrickwallLimiter to drive gain reduction from inter-sample peaks,
     * so the dBTP ceiling is honored against ISPs — not just sample peaks.
     * noexcept, allocation-free, callable from the audio thread.
     *
     * @p delayLen must be ≥ kFIRTaps and the ring must hold at least kFIRTaps
     * valid samples behind @p pos (the caller's delay line satisfies this).
     */
    static float truePeakAt(const float* delay, int delayLen, int pos) noexcept;

private:
    // 4-phase × 64-tap polyphase FIR coefficients (auto-generated by
    // scripts/generate_truepeak_coeffs.py from a 256-tap Kaiser β=8.6 prototype).
    // Phase interleaving: phases 0,1,2,3 correspond to fractional delays 0, 1/4, 2/4, 3/4
    static const float kPolyCoeffs[kUpsampleFactor][kFIRTaps];

    // Per-channel delay line (length = kFIRTaps)
    std::array<float, kFIRTaps> delayL_{}, delayR_{};
    int delayPos_ = 0;

    std::atomic<float> peakL_  { -std::numeric_limits<float>::infinity() };
    std::atomic<float> peakR_  { -std::numeric_limits<float>::infinity() };
    std::atomic<float> peak_   { -std::numeric_limits<float>::infinity() };
    std::atomic<float> peakLin_{ 0.0f };

    static float applyPhase(const float* delay, int pos,
                             const float* coeff, int taps) noexcept;
};

} // namespace more_phi
