/*
 * More-Phi — Core/TruePeakEstimator.cpp
 *
 * 4x polyphase FIR true peak estimator (ITU-R BS.1770-4 / EBU R128 Appendix 2).
 *
 * MEASUREMENT-GRADE filter (R3 / W10 fix, 2026-07-16): 4 phases x 64 taps,
 * polyphase-decomposed from a 256-tap linear-phase low-pass at
 * fc = 0.125 * fs_up_Nyquist, Kaiser windowed with beta = 8.6 (~80 dB stopband).
 * Matches the reference reconstruction in TestTruePeakEstimator.cpp
 * (referenceUpsample4x, protoTaps=256, beta=8.6) and eliminates the ~25 dB
 * near-Nyquist under-read the prior 48-tap beta=5.0 prototype exhibited.
 *
 * Regenerate the coefficient table below with:
 *   python3 scripts/generate_truepeak_coeffs.py
 */
#include "TruePeakEstimator.h"
#include <algorithm>
#include <cstring>

namespace more_phi {

// ── Polyphase coefficients (auto-generated; stored as static const) ───────────
// Auto-generated by scripts/generate_truepeak_coeffs.py
// 4x polyphase decomposition of a 256-tap linear-phase
// low-pass (fc=0.125 of fs_up Nyquist, Kaiser beta=8.6, ~80 dB stopband).
// 64 taps per phase x 4 phases.
const float TruePeakEstimator::kPolyCoeffs[kUpsampleFactor][kFIRTaps] =
{
    // Phase 0 (delay = 0/4 sample)
    {
        -0.000000000f, +0.000000000f, -0.000000000f, -0.000000000f, -0.000000000f, +0.000000000f,
        +0.000000000f, -0.000000000f, -0.000000000f, +0.000000000f, -0.000000000f, -0.000000000f,
        -0.000000000f, +0.000000000f, -0.000000000f, -0.000000000f, -0.000000000f, +0.000000000f,
        -0.000000000f, -0.000000000f, -0.000000000f, +0.000000000f, -0.000000000f, +0.000000000f,
        -0.000000000f, +0.000000000f, -0.000000000f, +0.000000000f, -0.000000000f, +0.000000000f,
        -0.000000000f, +0.000000000f, +1.001779527f, +0.000000000f, -0.000000000f, +0.000000000f,
        -0.000000000f, +0.000000000f, -0.000000000f, +0.000000000f, -0.000000000f, +0.000000000f,
        -0.000000000f, +0.000000000f, -0.000000000f, -0.000000000f, -0.000000000f, +0.000000000f,
        -0.000000000f, -0.000000000f, -0.000000000f, +0.000000000f, -0.000000000f, -0.000000000f,
        -0.000000000f, +0.000000000f, -0.000000000f, -0.000000000f, +0.000000000f, +0.000000000f,
        -0.000000000f, -0.000000000f, -0.000000000f, +0.000000000f,
    },
    // Phase 1 (delay = 1/4 sample)
    {
        -0.000012402f, +0.000029456f, -0.000056808f, +0.000098051f, -0.000157501f, +0.000240249f,
        -0.000352217f, +0.000500208f, -0.000691949f, +0.000936145f, -0.001242546f, +0.001622022f,
        -0.002086694f, +0.002650103f, -0.003327489f, +0.004136187f, -0.005096244f, +0.006231328f,
        -0.007570116f, +0.009148395f, -0.011012327f, +0.013223616f, -0.015867929f, +0.019069171f,
        -0.023014884f, +0.028004248f, -0.034546212f, +0.043581539f, -0.057060054f, +0.079777122f,
        -0.127506254f, +0.300191302f, +0.901470073f, -0.179042684f, +0.097992829f, -0.066301077f,
        +0.049150856f, -0.038258453f, +0.030646070f, -0.024981898f, +0.020581887f, -0.017058971f,
        +0.014177618f, -0.011785947f, +0.009781126f, -0.008090462f, +0.006660508f, -0.005450496f,
        +0.004428252f, -0.003567587f, +0.002846594f, -0.002246527f, +0.001751055f, -0.001345761f,
        +0.001017818f, -0.000755757f, +0.000549324f, -0.000389370f, +0.000267777f, -0.000177399f,
        +0.000112004f, -0.000066221f, +0.000035491f, -0.000015998f,
    },
    // Phase 2 (delay = 2/4 sample)
    {
        -0.000022445f, +0.000049780f, -0.000092858f, +0.000157008f, -0.000248600f, +0.000375122f,
        -0.000545253f, +0.000768934f, -0.001057432f, +0.001423419f, -0.001881064f, +0.002446165f,
        -0.003136338f, +0.003971291f, -0.004973254f, +0.006167608f, -0.007583840f, +0.009256978f,
        -0.011229759f, +0.013555949f, -0.016305502f, +0.019572794f, -0.023490159f, +0.028251090f,
        -0.034152082f, +0.041673162f, -0.051646277f, +0.065648151f, -0.087066463f, +0.124724509f,
        -0.211003827f, +0.637435602f, +0.636801915f, -0.210374586f, +0.124104076f, -0.086459037f,
        +0.065057693f, -0.051076436f, +0.041127218f, -0.033632893f, +0.027761054f, -0.023031183f,
        +0.019146280f, -0.015912343f, +0.013196540f, -0.010904016f, +0.008964367f, -0.007323422f,
        +0.005938080f, -0.004773005f, +0.003798458f, -0.002988864f, +0.002321860f, -0.001777658f,
        +0.001338619f, -0.000988973f, +0.000714620f, -0.000502994f, +0.000342968f, -0.000224764f,
        +0.000139881f, -0.000081019f, +0.000041998f, -0.000017678f,
    },
    // Phase 3 (delay = 3/4 sample)
    {
        -0.000019840f, +0.000041636f, -0.000075441f, +0.000125201f, -0.000195612f, +0.000292177f,
        -0.000421249f, +0.000590089f, -0.000806906f, +0.001080918f, -0.001422423f, +0.001842898f,
        -0.002355148f, +0.002973521f, -0.003714243f, +0.004595914f, -0.005640253f, +0.006873220f,
        -0.008326726f, +0.010041240f, -0.012069889f, +0.014485021f, -0.017389114f, +0.020933688f,
        -0.025353922f, +0.031036537f, -0.038665264f, +0.049571624f, -0.066733161f, +0.098433382f,
        -0.179488703f, +0.901918453f, +0.299743710f, -0.127062585f, +0.079340436f, -0.056633284f,
        +0.043167434f, -0.034147291f, +0.027622760f, -0.022652770f, +0.018728042f, -0.015549043f,
        +0.012927876f, -0.010740275f, +0.008900224f, -0.007345685f, +0.006030185f, -0.004917656f,
        +0.003979176f, -0.003190867f, +0.002532516f, -0.001986658f, +0.001537971f, -0.001172867f,
        +0.000879220f, -0.000646184f, +0.000464068f, -0.000324247f, +0.000219097f, -0.000141934f,
        +0.000086964f, -0.000049230f, +0.000024550f, -0.007102162f,
    },
};


// ── Lifecycle ─────────────────────────────────────────────────────────────────

TruePeakEstimator::TruePeakEstimator()
{
    delayL_.fill(0.f);
    delayR_.fill(0.f);
}

void TruePeakEstimator::prepare(double /*sampleRate*/, int /*maxBlockSize*/) noexcept
{
    reset();
}

void TruePeakEstimator::reset() noexcept
{
    delayL_.fill(0.f);
    delayR_.fill(0.f);
    delayPos_ = 0;
    peakL_.store(-std::numeric_limits<float>::infinity(), std::memory_order_relaxed);
    peakR_.store(-std::numeric_limits<float>::infinity(), std::memory_order_relaxed);
    peak_.store(-std::numeric_limits<float>::infinity(), std::memory_order_relaxed);
    peakLin_.store(0.0f, std::memory_order_relaxed);
}

// ── Internal: apply one polyphase subfilter ───────────────────────────────────

float TruePeakEstimator::applyPhase(const float* delay, int pos,
                                     const float* coeff, int taps) noexcept
{
    float acc = 0.0f;
    for (int k = 0; k < taps; ++k)
    {
        const int readIdx = (pos - k + taps) % taps;
        acc += coeff[k] * delay[readIdx];
    }
    return acc;
}

float TruePeakEstimator::truePeakAt(const float* delay, int delayLen, int pos) noexcept
{
    // Max over all 4 polyphase phases of the kFIRTaps samples ending at @p pos.
    // Generalized ring indexing (delayLen may differ from kFIRTaps) so this
    // works against BrickwallLimiter's wide lookahead ring as well as the
    // estimator's own kFIRTaps-length delay line.
    float peak = 0.0f;
    for (int ph = 0; ph < kUpsampleFactor; ++ph)
    {
        float acc = 0.0f;
        for (int k = 0; k < kFIRTaps; ++k)
        {
            const int readIdx = (pos - k + delayLen) % delayLen;
            acc += kPolyCoeffs[ph][k] * delay[readIdx];
        }
        const float a = acc < 0.0f ? -acc : acc;
        if (a > peak) peak = a;
    }
    return peak;
}

// ── Audio thread ──────────────────────────────────────────────────────────────

void TruePeakEstimator::processBlock(const juce::AudioBuffer<float>& buf) noexcept
{
    const int ns  = buf.getNumSamples();
    const int nch = std::min(buf.getNumChannels(), kMaxChannels);

    float maxL = 0.0f, maxR = 0.0f;

    for (int i = 0; i < ns; ++i)
    {
        // Feed new sample into delay line
        if (nch >= 1) delayL_[static_cast<size_t>(delayPos_)] = buf.getReadPointer(0)[i];
        if (nch >= 2) delayR_[static_cast<size_t>(delayPos_)] = buf.getReadPointer(1)[i];

        // Apply all 4 polyphase subfilters to get 4 interpolated samples per input sample
        for (int ph = 0; ph < kUpsampleFactor; ++ph)
        {
            if (nch >= 1)
            {
                const float s = applyPhase(delayL_.data(), delayPos_,
                                            kPolyCoeffs[ph], kFIRTaps);
                const float a = s < 0.0f ? -s : s;
                if (a > maxL) maxL = a;
            }
            if (nch >= 2)
            {
                const float s = applyPhase(delayR_.data(), delayPos_,
                                            kPolyCoeffs[ph], kFIRTaps);
                const float a = s < 0.0f ? -s : s;
                if (a > maxR) maxR = a;
            }
        }

        delayPos_ = (delayPos_ + 1) % kFIRTaps;
    }

    // Convert to dBTP and store
    auto toDB = [](float x) noexcept -> float {
        return x < 1e-12f ? -std::numeric_limits<float>::infinity()
                          : 20.0f * std::log10(x);
    };

    if (nch >= 1) peakL_.store(toDB(maxL), std::memory_order_relaxed);
    if (nch >= 2) peakR_.store(toDB(maxR), std::memory_order_relaxed);

    const float maxStereo = std::max(maxL, maxR);
    peak_.store(toDB(maxStereo), std::memory_order_relaxed);
    peakLin_.store(maxStereo, std::memory_order_relaxed);
}

} // namespace more_phi
