#!/usr/bin/env python3
"""
Generate 4x polyphase FIR coefficients for the TruePeak estimator.

Produces the SAME filter the TestTruePeakEstimator.cpp reference reconstruction
uses (protoTaps=256, Kaiser β=8.6, fc=0.125 of fs_up Nyquist, DC gain = L=4),
polyphase-decomposed into 4 phases x 64 taps so the estimator can compute the
4 interpolated samples per input sample directly without an explicit upsample.

Output: a C++ snippet with the coefficient array, printed to stdout.

This eliminates the ~25 dB near-Nyquist under-read documented in
TruePeakEstimator.h (the old 48-tap β=5.0 prototype had poor HF response).
With the 256-tap β=8.6 prototype, stopband attenuation is ~80 dB and the
estimator matches the reference reconstruction to within numerical noise.
"""
import math
from scipy.special import i0  # modified Bessel I0

PROTO_TAPS = 256      # full linear-phase prototype length (must match test ref)
UPSAMPLE   = 4        # 4x polyphase decomposition
BETA       = 8.6      # Kaiser window beta (~80 dB stopband)
FC         = 0.125    # cutoff as a fraction of fs_up Nyquist (fs_up = 4*fs)


def kaiser(n, M, beta):
    ratio = (2.0 * n) / M - 1.0
    arg2 = 1.0 - ratio * ratio
    if arg2 <= 0.0:
        return 1.0
    return i0(beta * math.sqrt(arg2)) / i0(beta)


def main():
    M = PROTO_TAPS - 1
    half = PROTO_TAPS // 2
    kpi = math.pi

    # 1. Design the linear-phase low-pass prototype (sinc x Kaiser).
    h = [0.0] * PROTO_TAPS
    h_sum = 0.0
    for n in range(PROTO_TAPS):
        k = n - half
        if k == 0:
            sinc = 2.0 * FC
        else:
            sinc = math.sin(2.0 * kpi * FC * k) / (kpi * k)
        w = kaiser(n, M, BETA)
        h[n] = sinc * w
        h_sum += h[n]

    # Normalize DC gain to L (so DC in -> DC out at same amplitude; the
    # zero-stuffed path would otherwise attenuate by 1/L).
    gain = UPSAMPLE / h_sum
    h = [v * gain for v in h]

    # 2. Polyphase decomposition: phase p collects taps p, p+L, p+2L, ...
    # Each phase is a length-(PROTO_TAPS/UPSAMPLE) sub-filter.
    taps_per_phase = PROTO_TAPS // UPSAMPLE
    phases = [[0.0] * taps_per_phase for _ in range(UPSAMPLE)]
    for n in range(PROTO_TAPS):
        p = n % UPSAMPLE
        i = n // UPSAMPLE
        if i < taps_per_phase:
            phases[p][i] = h[n]

    # 3. Emit C++ (float, %.9f — enough precision, matches existing style).
    print("// Auto-generated by scripts/generate_truepeak_coeffs.py")
    print(f"// 4x polyphase decomposition of a {PROTO_TAPS}-tap linear-phase")
    print(f"// low-pass (fc={FC} of fs_up Nyquist, Kaiser beta={BETA}, ~80 dB stopband).")
    print(f"// {taps_per_phase} taps per phase x {UPSAMPLE} phases.")
    print("const float TruePeakEstimator::kPolyCoeffs[kUpsampleFactor][kFIRTaps] =")
    print("{")
    for p in range(UPSAMPLE):
        coeffs = phases[p]
        # Wrap rows of 6 for readability, matching the existing file's style.
        print(f"    // Phase {p} (delay = {p}/{UPSAMPLE} sample)")
        print("    {")
        for i in range(0, taps_per_phase, 6):
            chunk = coeffs[i:i + 6]
            # Comma-separated, trailing comma on each row (last row's comma is
            # harmless in an initializer list).
            joined = ", ".join(f"{c:+.9f}f" for c in chunk)
            print(f"        {joined},")
        print("    },")
    print("};")


if __name__ == "__main__":
    main()
