# GenerateModelHash.cmake
# Compute SHA-256 of a file and emit a C++ header with the digest as a hex string.
# Used by the ONNX model integrity check in SonicMasterDecisionRunner.
#
# Usage:
#   include(cmake/GenerateModelHash.cmake)
#   generate_model_hash("/path/to/model.onnx" "/path/to/output/SonicMasterModelHash.h")
#
# On Windows (no native sha256sum) falls back to certutil -hashfile.
# On macOS/Linux uses `shasum -a 256` or `sha256sum`.

function(generate_model_hash INPUT_FILE OUTPUT_HEADER)
    get_filename_component(out_dir "${OUTPUT_HEADER}" DIRECTORY)
    file(MAKE_DIRECTORY "${out_dir}")

    # Use CMake's built-in file(SHA256 ...) — native, cross-platform, no external
    # tool dependency. (The earlier certutil/shasum path failed silently on
    # Windows because certutil wasn't resolvable through cmake -E env, producing
    # an all-zero placeholder hash that would make the runtime integrity check
    # reject every bundled model.)
    if(EXISTS "${INPUT_FILE}")
        file(SHA256 "${INPUT_FILE}" computed_hash)
        string(TOLOWER "${computed_hash}" computed_hash)
    else()
        message(WARNING "generate_model_hash: ${INPUT_FILE} does not exist — "
            "using placeholder hash. Model integrity check will be skipped at runtime.")
        set(computed_hash "0000000000000000000000000000000000000000000000000000000000000000")
    endif()

    # Emit the header
    set(header_content "// Generated by GenerateModelHash.cmake — DO NOT EDIT
#pragma once

namespace more_phi {
namespace sonicmaster {

// SHA-256 of ${INPUT_FILE}
inline constexpr const char* kExpectedModelHash = \"${computed_hash}\";

} // namespace sonicmaster
} // namespace more_phi
")
    file(WRITE "${OUTPUT_HEADER}" "${header_content}")
    message(STATUS "generate_model_hash: ${computed_hash} -> ${OUTPUT_HEADER}")
endfunction()
