# GenerateModelHash.cmake
# Compute SHA-256 of a file and emit a C++ header with the digest as a hex string.
# Used by the ONNX model integrity check in SonicMasterDecisionRunner.
#
# Usage:
#   include(cmake/GenerateModelHash.cmake)
#   generate_model_hash("/path/to/model.onnx" "/path/to/output/SonicMasterModelHash.h")
#
# On Windows (no native sha256sum) falls back to certutil -hashfile.
# On macOS/Linux uses `shasum -a 256` or `sha256sum`.

function(generate_model_hash INPUT_FILE OUTPUT_HEADER)
    get_filename_component(out_dir "${OUTPUT_HEADER}" DIRECTORY)
    file(MAKE_DIRECTORY "${out_dir}")

    if(WIN32)
        set(hash_cmd
            "${CMAKE_COMMAND}" -E env "PATH=$ENV{PATH}"
            certutil -hashfile "${INPUT_FILE}" SHA256
        )
    elseif(APPLE)
        set(hash_cmd shasum -a 256 "${INPUT_FILE}")
    else()
        set(hash_cmd sha256sum "${INPUT_FILE}")
    endif()

    execute_process(
        COMMAND ${hash_cmd}
        OUTPUT_VARIABLE hash_output
        RESULT_VARIABLE hash_result
        ERROR_QUIET
    )

    if(NOT hash_result EQUAL 0)
        message(WARNING "generate_model_hash: could not compute SHA-256 for ${INPUT_FILE} — "
            "using placeholder hash. Model integrity check will be skipped at runtime.")
        set(computed_hash "0000000000000000000000000000000000000000000000000000000000000000")
    else()
        # Extract the hex digest — first token in the output (certutil
        # outputs a colon-separated hex string with spaces, sha*sum outputs
        # "hash  filename"). Normalise to lowercase 64-char hex.
        string(REGEX MATCHALL "[0-9a-fA-F]+" hash_tokens "${hash_output}")
        list(GET hash_tokens 0 computed_hash)
        string(TOLOWER "${computed_hash}" computed_hash)
    endif()

    # Emit the header
    set(header_content "// Generated by GenerateModelHash.cmake — DO NOT EDIT
#pragma once

namespace more_phi {
namespace sonicmaster {

// SHA-256 of ${INPUT_FILE}
inline constexpr const char* kExpectedModelHash = \"${computed_hash}\";

} // namespace sonicmaster
} // namespace more_phi
")
    file(WRITE "${OUTPUT_HEADER}" "${header_content}")
    message(STATUS "generate_model_hash: ${computed_hash} → ${OUTPUT_HEADER}")
endfunction()
